[package]
name = "SimpleToken"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
simple_token = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]

[dev-dependencies]
